//! mailffi — the shared library the Flutter frontend loads in-process.
//!
//! This crate is to Flutter what `mailapp` is to QML: a thin, UI-free
//! adapter over [`mailcore`]. It holds no mail logic of its own. The Dart
//! side calls it through `flutter_rust_bridge` (`dart:ffi` under the hood,
//! same process, no subprocess and no socket), so a call is a function call
//! across the FFI boundary rather than an IPC round-trip.
//!
//! Two rules keep it honest, mirroring `AGENT.md` §2:
//!
//! - **No mail logic here.** Every function in [`api`] is a translation of
//!   arguments into a `mailcore` call and its result into something Dart can
//!   hold. Anything that needs a decision belongs in `mailcore`.
//! - **No blocking work on Dart's UI isolate.** Pure SQLite reads are fast
//!   enough to answer inline; anything that touches IMAP or SMTP is queued
//!   onto the `mailclient-net` thread ([`net`]) and reported back over the
//!   [`api::events`] stream.
//!
//! ## How this differs from the Qt bridge
//!
//! `mailapp` keeps the current account/folder inside the `Bridge` QObject and
//! pushes rebuilt JSON feeds into QML properties. Here the **Dart side owns
//! the selection**: every read takes the ids explicitly and returns JSON, and
//! a finished job only says *that* something changed so Dart can re-read what
//! it is actually showing. That removes the stale-selection reconciliation
//! `mailapp`'s worker has to do, and it fits Flutter's state model.

mod db;
mod net;
mod session;

pub mod api;

// Generated by `flutter_rust_bridge_codegen` from the `api` module — see
// `flutter/README.md`. Checked in so a plain `cargo build` works without the
// codegen tool installed.
mod frb_generated;
